### ISSUE TITLE
how do we integrate with oauth2 client

### ISSUE THREAD

**Issue by mohamed-azeem** [maciejwalkowiak/spring-boot-http-clients#6]
Hi @maciejwalkowiak 

is it possible to show an example consuming an API(mock one) that requires oauth token, for eg adding below lib

spring-boot-starter-oauth2-client

**Comment by maciejwalkowiak** [comment]
@mohamed-azeem how would you do it with pure WebClient?

**Comment by mohamed-azeem** [comment]
ya got it
