### ISSUE TITLE
Cannot configure headers in application.yml

### ISSUE THREAD

**Issue by jakubszybisty** [maciejwalkowiak/spring-boot-http-clients#7]
Hi! Does the released version contain the same source code as the one in github repository? I can see on my machine, that it doesn't contain code for configuring headers in application.yml

**Comment by jakubszybisty** [comment]
No problem. Any ETA on the new version?

**Comment by maciejwalkowiak** [comment]
Apologies @jakubszybisty, i forgot! It is released now https://github.com/maciejwalkowiak/spring-boot-http-clients/releases/tag/v0.1.1
